backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "projects"
    label: "Projects"
    label_singular: "Project"
    folder: "content/projects"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "period", label: "Period", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "tags", label: "Tags", widget: "list", field: { label: "Tag", name: "tag", widget: "string" } }
      - { name: "body", label: "Body", widget: "markdown" }
  - name: "news"
    label: "News & Events"
    label_singular: "News"
    folder: "content/news"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "date", format: "MMMM D, YYYY" }
      - { name: "location", label: "Location", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "body", label: "Body", widget: "markdown" }

